import type { Metadata } from "next";
import Sidebar from "../../components/sidebarcomponents/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-full flex">
        <div >
            <Sidebar/>
        </div>
        <div className="w-fit p-7 overflow-y-scroll max-h-screen">
            {children}
        </div>
    </div>
  );
}
